// default package
// Generated Nov 2, 2013 4:26:34 PM by Hibernate Tools 3.4.0.CR1
package com.spring.mvc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.springframework.transaction.annotation.Transactional;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address",catalog="test")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3190492553055522796L;
	
	private String id;
	private User user;
	private String strnum;
	private String strname;
	private String city;
	private String state;
	private String zip;

	public Address() {
	}

	public Address(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public Address(String id, User user, String strnum, String strname,
			String city, String state, String zip) {
		this.id = id;
		this.user = user;
		this.strnum = strnum;
		this.strname = strname;
		this.city = city;
		this.state = state;
		this.zip = zip;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "strnum", length = 15)
	public String getStrnum() {
		return this.strnum;
	}

	public void setStrnum(String strnum) {
		this.strnum = strnum;
	}

	@Column(name = "strname", length = 100)
	public String getStrname() {
		return this.strname;
	}

	public void setStrname(String strname) {
		this.strname = strname;
	}

	@Column(name = "city", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

}
