// default package
// Generated Nov 2, 2013 4:26:34 PM by Hibernate Tools 3.4.0.CR1
package com.spring.mvc.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.springframework.transaction.annotation.Transactional;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user",catalog="test")
public class User implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7592089611356697979L;
	
	private String id;
	private String fname;
	private String mname;
	private String lname;
	private Set<Address> addresses = new HashSet<Address>(0);

	public User() {
	}

	public User(String id, String fname, String lname) {
		this.id = id;
		this.fname = fname;
		this.lname = lname;
	}

	public User(String id, String fname, String mname, String lname,
			Set<Address> addresses) {
		this.id = id;
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.addresses = addresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "fname", nullable = false, length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "mname", length = 50)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "lname", nullable = false, length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    @JsonIgnore
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
